version: "3"

services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dull
      - POSTGRES_PASSWORD=dull
      - POSTGRES_DB=builders_db
    
    restart: always
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    restart: on-failure
    ports:
      - "8080:8080"
volumes:
  postgres_data:
